# Generated by Django 4.2.7 on 2023-12-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('good_or_bad', models.CharField(blank=True, max_length=5, null=True)),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='saApp.product')),
            ],
        ),
    ]
